### ISSUE TITLE
他者へのNFT mintに関するテストを追加

### ISSUE THREAD

**Issue by bioerrorlog** [Japan-DfinityInfoHub/generative-art-nft#14]
# 概要・目的
他者へのNFT mintに関するテストを追加し、誰に対してmint出来るのかを明示する。

# AsIs
他者へのNFT mintに関するテストがない

# ToBe
他者へのNFT mintに関する振る舞いがテストで保障されている

# タスク

**Comment by bioerrorlog** [comment]
@hoosan @ClankPan 
mintNFTでのmint先(request.to)には別に制限を設けないイメージでしたが認識合いますか？
(誰にでもmintできる)

**Comment by hoosan** [comment]
はい、制限なしで良いと思います
