### ISSUE TITLE
GenerativeArt生成を行うスクリプトの作成

### ISSUE THREAD

**Issue by bioerrorlog** [Japan-DfinityInfoHub/generative-art-nft#20]
# 概要・目的

~~適当な数(1000個くらい)のgenerative art生成 & NFT mintを行うスクリプトを用意する。~~

ts-nodeでpngをバックエンドでジェネラティブ生成する（npm run generate:images で実行されるイメージ。保存先はdist）
https://github.com/Japan-DfinityInfoHub/generative-art-nft/issues/7#issuecomment-1133868287

# AsIs
- Generative artをフロントで表示することを想定したコード(p5.js)がある #2

# ToBe
- ts-nodeでpngをバックエンドでジェネラティブ生成できる

# タスク
※ NFTアセット生成/管理方法に関するタスク全体は下記参照

https://github.com/Japan-DfinityInfoHub/generative-art-nft/issues/7#issuecomment-1133868287

**Comment by hoosan** [comment]
@bioerrorlog 
Mintと画像データのCanisterへの保存は分け、`_tokenImage : HashMap<TokenIndex, Blob>`で管理するのはどうでしょうか？ （`_tokenImage`への書き込み権限をinstallerにして）shellスクリプトでローカルの画像をbase64に変換して登録する処理と、Mint（TokenIndexとPrincipalの対応付け）は分離できると思います🙏
後、画像データそのものはgitで管理しなくてもいいかなと思いましたがどうでしょうか？
（テストするときは画像生成→登録処理を毎回行う）

**Comment by hoosan** [comment]
@bioerrorlog 
画像生成のコードを統合するなら上記のテストフローが良いですが、リポジトリ分けるなら画像で管理して入れ替え・追加する方が良いですね。この辺りご意見いただければ🙏

**Comment by bioerrorlog** [comment]
下記議論済み (with @hoosan )

- 画像はgit管理しない
- 画像管理は`_tokenImage : HashMap<TokenIndex, Blob>`で持つ
- 1000個mintしたい場合は、下記の３つの仕組み(script的な)があればよい
  - generative artを1000個生成する (pngをlocal保存) 
  - _tokenImage にその画像を1000個登録する
  - mintNFTを1000回行う
- p5.jsのgenerative artコードは本レポジトリに配置する

**Comment by hoosan** [comment]
#30 によりFix
