### ISSUE TITLE
DABへの登録方法調査

### ISSUE THREAD

**Issue by bioerrorlog** [Japan-DfinityInfoHub/generative-art-nft#6]
# 概要・目的
DABの仕様を改めて調査し、どのようなNFT canister (特にasset canister)を用意すればDABに登録できるのかを明確にする。

NFT asset canister でtokenidからジェネラティブに生成した画像を表示する想定でいるが、ほんとにそれでいいんだっけ？を明確にする

# AsIs
なんとなくDABに登録できると思っている。

# ToBe
DABに登録するための条件と登録までの道筋が明確化される。

# タスク

**Comment by bioerrorlog** [comment]
DAB document
https://docs.dab.ooo/

**Comment by bioerrorlog** [comment]
DAB登録申請フォーム：
DAB - NFT List Submission
https://dab-ooo.typeform.com/nft-list?typeform-source=dab.ooo

申請項目

1. What's your NFT Collection's Name?This question is required. *
This name will be added in the collection's metadata in DAB as the project's official name.
2. Please provide a link to your project's website. This question is required.*
(If none is available, link to an official social handle)
3. Brief description of the projectThis question is required. *
Provide a description of 1/2 lines that will be added as a metadata description to your NFT collection in DAB.
4. Please specify the NFT standard/interface your NFT follows, and a link to its repository.This question is required. *
(e.g EXT Standard, Departure Labs Standard)
5. Upload Logo/Icon - 400x400pxThis question is required. *
This will be used as the collection's logo in DAB's list.
6. Number of items in the collectionThis question is required. *
(e.g. 10,000 initial mint; or undefined if it will grow continuously)
7. Please provide a GitHub link to an open source repository for the NFT project/canister. This question is required.*
If not available, or not open source yet, specify that and suggest a timeline to it being open source.
8. Specify the NFT collection's Canister ID. This question is required.*
(If not deployed yet, specify "not deployed")
9. Is the project release, or to be released?This question is required. *
(If not released, specify a tentative date)
10. Please provide us the best method to reach out to you for any clarifying questions or updates.
(Discord, Twitter, Email)
11. DockerHub/GitHub Image URL (optional).
Now, we are going to ask for your project's build information (optional).
This last section is optional. The DAB team can verify the canister's build by replicating the build in order to verify the same WASM hash as deployed on the IC.
To do so, please provide a Docker image that contains your build environment and steps (Rust/Motoko version, Build flags, Targets if other than default `wasm32-unknown-unknown` target).

備考
- 申請後にDAB teamとやり取りしながら登録処理を進めていく流れになりそう(申請項目から機械的に登録処理が行われるわけではなさそう)
- Project release前/Canister deploy前でも申請はできる
- 申請段階ではBackend Canister Idのみを申請、Asset canisterに関する情報は申請項目にない

**Comment by bioerrorlog** [comment]
温度感的に今回DAB登録ほんとにするの？不要では？
が今の考え。 (with @hoosan )

**Comment by hoosan** [comment]
こちら、今回のNFTはデモ用であり将来的に消す可能性があるということで、DABへの登録はしなくて良いかなと思います。
登録の内容や仕方がわかったので勉強になりました。

**Comment by bioerrorlog** [comment]
↑により、本issueはClose.
