### ISSUE TITLE
NFTアセット生成/管理機能の追加

### ISSUE THREAD

**Issue by bioerrorlog** [Japan-DfinityInfoHub/generative-art-nft#7]
# 概要・目的
NFTアセット(generative art)の生成/運用方法を検討し、実装する。

これまで想定していた方法(backendではtokenidのみ保持、フロント側でtokenidを入力としてgenerative artを生成)では以下の考慮点が挙がっている。
- NFT表示時にフロント側で毎回generative art生成ロジックを走らせるのは処理が重い(時間がかかる)。
(生成ロジックを調整して処理を軽くすることは可能だが、それでもNFTのlist表示に耐えられるかの保証はない)
- (ICにおいては)一般的にはNFT画像を直接backendに保持し、backendへのcallで取得することが多い(ようにみえる)。
- この辺りを考えると、フロント側で都度生成ではなく、mint時にbackend登録(or asset canister登録, etc..)、などの選択肢も挙がってくるのではないか。
- とはいえ今回の用途(nft-barterで利用)では、想定していた方法(asset canisterでgenerative画像生成)で画像をasset canisterに取得しに行く、という選択肢も残る。

上記を踏まえてNFTアセット運用方法を検討し、実装する。

関連Issue
#2 #6 

# AsIs
- backendではtokenidのみ保持、フロント側でtokenidを入力としてNFTアセット(generative art)を生成させればよいと考えている
- その実装はまだない
(generative artロジック部分の検討は #2 で進行中)

# ToBe
- NFTアセット生成/管理方法が決まる
- その機能が実装されている

# タスク
- [x] NFTアセット生成/管理方法の決定
- [ ] NFTアセット生成/管理機能の実装

**Comment by hoosan** [comment]
@bioerrorlog 
他のNFTとの互換性を考えて、バックエンドCanister にデータを保存&httpリクエストに対して画像を返すという実装が良いのではないかと思いました。アセットの数はとりあえず1000個とか適当な数で、適宜増やしていけばいいかなと。NFTに対して価値が出ないようにという意味では、このNFTはデモ用でありそのうち消す予定であると明記すれば問題ないと思います。

**Comment by bioerrorlog** [comment]
[Memo]
CanisterのHttpレスポンス実装例
- Motokoの実装例
https://github.com/nomeata/motoko-certified-http
https://github.com/Toniq-Labs/creator-nfts
- NFT canister (DIP721)における実装例 (Rust)
https://github.com/dfinity/examples/tree/master/rust/dip721-nft-container
- Asset canisterの実装 (の実態として使われているlibrary) (Rust)
https://github.com/dfinity/cdk-rs/tree/main/src/ic-certified-assets

**Comment by hoosan** [comment]
# NFTアセット生成/管理方法

- [x] #20 
ts-nodeでpngをバックエンドでジェネラティブ生成する（`npm run generate:images` で実行されるイメージ。保存先は`dist`）
イメージデータのGit管理は行わない
- [x] #26
- [x] 画像データは<TokenId, Blob>のハッシュマップとしてCanisterに保存する
#24 
- [ ] #27
`setTokenImage` メソッドを ts-node で呼び、Canister に登録する（`npm run upload:images`で実行されるイメージ） 
- [x] `/?tokenid=*****` で画像が返される
#24  


@bioerrorlog 確認お願いします🙏

**Comment by bioerrorlog** [comment]
@hoosan 
整理ありがとうございます:pray:
認識あいます！
