### ISSUE TITLE
minter の制限削除

### ISSUE THREAD

**Issue by hoosan** [Japan-DfinityInfoHub/generative-art-nft#8]
# 概要・目的
誰でもmintできるようにする

# AsIs
mintNFTに以下のassertがある。
```
assert(msg.caller == _minter);
```
_minterをセットする関数であるsetMinterにも同様のassertがあり、要は運営しかmintができないようになっている。

# ToBe
誰でもmintできるようになる

# タスク

**Comment by bioerrorlog** [comment]
PR merged #10
